VidlyCore/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace VidlyCore.Controllers
{
    public class RentalsController : Controller
    {
        public IActionResult New()
        {
            return View();
        }
    }
}

VidlyCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - VidlyCore_</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-lumen.css" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-theme.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	@RenderSection("Styles", required: false)
</head>
<body>
	<partial name="_NavBar.cshtml" />
	<div class="container body-content">
		@RenderBody()
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2020 - VidlyCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
	<script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/modernizr.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>

VidlyCore/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			@Html.ActionLink("Vidly", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li>@Html.ActionLink("New Rental", "New", "Rentals")</li>
				<li>@Html.ActionLink("Customers", "Index", "Customers")</li>
				<li>@Html.ActionLink("Movies", "Index", "Movies")</li>
			</ul>
			<partial name="_LoginPartial" />
		</div>
	</div>
</div>